title: Eric Stieber # your name (or website title) here
logo: "images/Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/ericstieber/">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/etstieber/">GitHub</a>  
 
  
theme: jekyll-theme-minimal
